language: cpp

sudo: required

services:
  -docker

before_install:
  - docker pull tkzdockerid/coarct-testenv:clang-6-1
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"
  - sudo apt-get install -y clang-4.0 libclang-common-4.0-dev libclang-4.0-dev
  - sudo apt-get install -y llvm-4.0 llvm-4.0-dev

script:
  - git clone https://github.com/lanl/CoARCT.git -b clang-6.0 coarct
  - cd coarct
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=on -j 4 2>&1 | tee make.out
  - ./test/corct_unittests
