language: cpp

sudo: required

services:
  - docker

compiler:
  - clang

before_install:
  - docker pull tkzdockerid/coarct-testenv:clang-7-0-B

script:
  - docker run -it tkzdockerid/coarct-testenv:clang-7-0-B /bin/bash test_coarct.sh
